# Use Ubuntu as the base image
FROM ubuntu:latest

# Update package lists and install Python3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip

# Set the new index-url and install additional packages
RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip3 install accelerate==0.21.0 transformers==4.31.0 xformers flask torch

# Set the working directory
WORKDIR /app